### ISSUE TITLE
Can I use it with js-ipfs-api

### ISSUE THREAD

**Issue by joaosantos15** [ipfs-shipyard/y-ipfs-connector#5]
Hello,
I'm looking to create a key-value store using IPFS. I was told that Y.js could be used for this. I'm using the go-ipfs implementation with the js-ipfs-api in node.js. I tried adapting [this example](https://github.com/ipfs-shipyard/shared-editing-demo) to get the connector working with the js-ipfs-api, but without success. Can they work together or does the connector only work with js-ipfs?
Thanks! :)

**Comment by pgte** [comment]
Y-ipfs-connector only works with js-ipfs because it needs to establish direct p2p connections with a custom protocol and go-ipfs does not support that.

**Comment by joaosantos15** [comment]
Ok, thank you for the clarification. I'll have to look for an alternative then. 🙂
