### ISSUE TITLE
Question: Can I use leveldb for storage? 

### ISSUE THREAD

**Issue by kidinamoto01** [ipfs-shipyard/y-ipfs-connector#6]
Hello, there

I'd love to ask a question about the storage of yes, can we use leveledb or indexedb?

Thanks so  much.

**Comment by pgte** [comment]
@kidinamoto01 that's a question you should ask to Y.js maintainers, but I can tell you that yes, you can use it. There's a leveldb adaptor in the modules section of the Y.js website:
http://y-js.org/#!/modules
