### ISSUE TITLE
whenSynced only firing once when user is connected to same peer in more than one room

### ISSUE THREAD

**Issue by AquiGorka** [ipfs-shipyard/y-ipfs-connector#8]
From what I can see/understand if nodes A and B both have two instances of Y configured to two different rooms and want to connect to each other in both rooms the whenSynced listener is only executed for the last room joined.

Sync done should be aware a user can be connected in more than one room and fire more than once  (whenSynced callback) right?

**Comment by pgte** [comment]
There is no place in this connector where it fires the `whenSynced` event, so perhaps this is a y.js issue?

**Comment by AquiGorka** [comment]
I thought so too, but the way I read into this, is this `connector` extends on `YJS connector` and that connector might not be responsible for the behaviour I describe.

The concept of rooms is implemented here, so maybe this tool should be responsible for adding such events–I added the issue in the `YJS` repo as well to discuss and find out where/why/how.

**Comment by pgte** [comment]
Hi Gorka,

The connectors in Y.js are not directly responsible for this.
As you can see in the official Y.js webrct connector, it's structurally very similar to the IPFS connector:

y.js webrtc: https://github.com/y-js/y-webrtc/blob/master/src/WebRTC.js
IPFS connector: https://github.com/ipfs-shipyard/y-ipfs-connector/blob/master/src/index.js

Have you tried with the WebRTC connector using the same Y.js version and check if this happens?

**Comment by AquiGorka** [comment]
Thanks for your feedback @pgte, I am waiting to see if I get a response from `YJS` and actually have been working on a solution myself. I'll keep this thread posted.

I'll review the `webrtc` connector too and it makes sense that this is something that `YJS` should take care of.

**Comment by AquiGorka** [comment]
This stopped happening when I updated to yjs-ipfs-connector's latest version.

Thanks @pgte for the help.
